version: "1.0"

services:
  owlharbour:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8081"
    networks:
      - owlharbour-network

networks:
  owlharbour-network:
    driver: bridge
